spring:
  application:
    name: CadastroAPI

  datasource:
    url: jdbc:postgresql://localhost:5432/cadastro_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

